    name: GitHub Classroom Workflow

    on: 
      push: 
        #paths: 
          # Do not run workflow unless these files were modified
        #  - 'assignment.py' 
        #  - 'test_assignment.py' 

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
      check:
        uses: markpatterson27/GitHub-Classroom-Check-For-Changes/.github/workflows/change-check.yml@main
        with:
          paths: '.github'
